[package]
name = "lyric-resolution-changer-cli"
version = "0.2.0"
edition = "2021"
description = "Clone Hero chart file resolution changing made easy! cli version"
license-file = "LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
dhat = "0.3.2"
chart-file-parser = "0.1.0"

[features]
dhat-heap = []

