[package]
name = "lyric-resolution-changer-cli"
version = "0.2.2"
authors = ["aragonnetje6"]
edition = "2021"
description = "Clone Hero chart file resolution changing made easy! cli version"
repository = "https://github.com/aragonnetje6/lyric-resolution-changer"
license-file = "LICENSE.md"
workspace = "../"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
dhat = "0.3.2"
chart-file-parser = "0.2.1"

[features]
dhat-heap = []

